In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as pltp
import seaborn as sns

In [2]:
data=pd.read_csv('diabetes.csv')
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
data.shape       #dimension of the dataset

(768, 9)

In [4]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

There is no null values in the data set

In [5]:
#correlation
data.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [6]:
len(data["Outcome"])

768

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
#Train Test
regressors=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
response =["Outcome"]

In [9]:
X=data[regressors].values
y=data[response].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=10)

In [10]:
print(len(data.loc[data["Pregnancies"]==0]))
print(len(data.loc[data["Glucose"]==0]))
print(len(data.loc[data["BloodPressure"]==0]))
print(len(data.loc[data["SkinThickness"]==0]))
print(len(data.loc[data["Insulin"]==0]))

111
5
35
227
374

In [11]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [12]:
newdata2=data.drop("Outcome",1).mask(data==0).fillna(data.mean())
newdata2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.000000,148.0,72.0,35.000000,79.799479,33.6,0.627,50
1,1.000000,85.0,66.0,29.000000,79.799479,26.6,0.351,31
2,8.000000,183.0,64.0,20.536458,79.799479,23.3,0.672,32
3,1.000000,89.0,66.0,23.000000,94.000000,28.1,0.167,21
4,3.845052,137.0,40.0,35.000000,168.000000,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10.000000,101.0,76.0,48.000000,180.000000,32.9,0.171,63
764,2.000000,122.0,70.0,27.000000,79.799479,36.8,0.340,27
765,5.000000,121.0,72.0,23.000000,112.000000,26.2,0.245,30
766,1.000000,126.0,60.0,20.536458,79.799479,30.1,0.349,47
767,1.000000,93.0,70.0,31.000000,79.799479,30.4,0.315,23

In [13]:
Outcome=data["Outcome"]
Outcome

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [14]:
newdata3=pd.concat([newdata2,Outcome],axis=1)
newdata3

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.0,72.0,35.000000,79.799479,33.6,0.627,50,1
1,1.000000,85.0,66.0,29.000000,79.799479,26.6,0.351,31,0
2,8.000000,183.0,64.0,20.536458,79.799479,23.3,0.672,32,1
3,1.000000,89.0,66.0,23.000000,94.000000,28.1,0.167,21,0
4,3.845052,137.0,40.0,35.000000,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10.000000,101.0,76.0,48.000000,180.000000,32.9,0.171,63,0
764,2.000000,122.0,70.0,27.000000,79.799479,36.8,0.340,27,0
765,5.000000,121.0,72.0,23.000000,112.000000,26.2,0.245,30,0
766,1.000000,126.0,60.0,20.536458,79.799479,30.1,0.349,47,1
767,1.000000,93.0,70.0,31.000000,79.799479,30.4,0.315,23,0

In [15]:
newdata3.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
newdata3.head(50)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.0,72.000000,35.000000,79.799479,33.600000,0.627,50,1
1,1.000000,85.0,66.000000,29.000000,79.799479,26.600000,0.351,31,0
2,8.000000,183.0,64.000000,20.536458,79.799479,23.300000,0.672,32,1
3,1.000000,89.0,66.000000,23.000000,94.000000,28.100000,0.167,21,0
4,3.845052,137.0,40.000000,35.000000,168.000000,43.100000,2.288,33,1
5,5.000000,116.0,74.000000,20.536458,79.799479,25.600000,0.201,30,0
6,3.000000,78.0,50.000000,32.000000,88.000000,31.000000,0.248,26,1
7,10.000000,115.0,69.105469,20.536458,79.799479,35.300000,0.134,29,0
8,2.000000,197.0,70.000000,45.000000,543.000000,30.500000,0.158,53,1
9,8.000000,125.0,96.000000,20.536458,79.799479,31.992578,0.232,54,1
10,4.000000,110.0,92.000000,20.536458,79.799479,37.600000,0.191,30,0
11,10.000000,168.0,74.000000,20.536458,79.799479,38.000000,0.537,34,1
12,10.000000,139.0,80.000000,20.536458,79.799479,27.100000,1.441,57,0
13,1.000000,189.0,60.000000,23.000000,846.000000,30.100000,0.398,59,1
14,5.000000,166.0,72.000000,19.000000,175.000000,25.800000,0.587,51,1
15,7.000000,100.0,69.105469,20.536458,79.799479,30.000000,0.484,32,1
16,3.845052,118.0,84.000000,47.000000,230.000000,45.800000,0.551,31,1
17,7.000000,107.0,74.000000,20.536458,79.799479,29.600000,0.254,31,1
18,1.000000,103.0,30.000000,38.000000,83.000000,43.300000,0.183,33,0
19,1.000000,115.0,70.000000,30.000000,96.000000,34.600000,0.529,32,1
20,3.000000,126.0,88.000000,41.000000,235.000000,39.300000,0.704,27,0
21,8.000000,99.0,84.000000,20.536458,79.799479,35.400000,0.388,50,0
22,7.000000,196.0,90.000000,20.536458,79.799479,39.800000,0.451,41,1
23,9.000000,119.0,80.000000,35.000000,79.799479,29.000000,0.263,29,1
24,11.000000,143.0,94.000000,33.000000,146.000000,36.600000,0.254,51,1
25,10.000000,125.0,70.000000,26.000000,115.000000,31.100000,0.205,41,1
26,7.000000,147.0,76.000000,20.536458,79.799479,39.400000,0.257,43,1
27,1.000000,97.0,66.000000,15.000000,140.000000,23.200000,0.487,22,0
28,13.000000,145.0,82.000000,19.000000,110.000000,22.200000,0.245,57,0
29,5.000000,117.0,92.000000,20.536458,79.799479,34.100000,0.337,38,0
30,5.000000,109.0,75.000000,26.000000,79.799479,36.000000,0.546,60,0
31,3.000000,158.0,76.000000,36.000000,245.000000,31.600000,0.851,28,1
32,3.000000,88.0,58.000000,11.000000,54.000000,24.800000,0.267,22,0
33,6.000000,92.0,92.000000,20.536458,79.799479,19.900000,0.188,28,0
34,10.000000,122.0,78.000000,31.000000,79.799479,27.600000,0.512,45,0
35,4.000000,103.0,60.000000,33.000000,192.000000,24.000000,0.966,33,0
36,11.000000,138.0,76.000000,20.536458,79.799479,33.200000,0.420,35,0
37,9.000000,102.0,76.000000,37.000000,79.799479,32.900000,0.665,46,1
38,2.000000,90.0,68.000000,42.000000,79.799479,38.200000,0.503,27,1
39,4.000000,111.0,72.000000,47.000000,207.000000,37.100000,1.390,56,1
40,3.000000,180.0,64.000000,25.000000,70.000000,34.000000,0.271,26,0
41,7.000000,133.0,84.000000,20.536458,79.799479,40.200000,0.696,37,0
42,7.000000,106.0,92.000000,18.000000,79.799479,22.700000,0.235,48,0
43,9.000000,171.0,110.000000,24.000000,240.000000,45.400000,0.721,54,1
44,7.000000,159.0,64.000000,20.536458,79.799479,27.400000,0.294,40,0
45,3.845052,180.0,66.000000,39.000000,79.799479,42.000000,1.893,25,1
46,1.000000,146.0,56.000000,20.536458,79.799479,29.700000,0.564,29,0
47,2.000000,71.0,70.000000,27.000000,79.799479,28.000000,0.586,22,0
48,7.000000,103.0,66.000000,32.000000,79.799479,39.100000,0.344,31,1
49,7.000000,105.0,69.105469,20.536458,79.799479,31.992578,0.305,24,0

In [17]:
regressors=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
response =["Outcome"]
X=newdata3[regressors].values
y=newdata3[response].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=10)

In [20]:
print(len(X_test))
print(len(X_train))

231
537

In [22]:
from sklearn.linear_model import LogisticRegression

In [24]:
logmod= LogisticRegression()
logmod.fit(X_train,y_train)

C:\Users\Raagu\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Raagu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

y_pred=logmod.predict(X_test)
y_pred

In [29]:
print("Accuracy",(logmod.score(X_test,y_test))) #Accuracy 74%

Accuracy 0.7402597402597403

In [ ]:
from sklearn.metrics import confusion_matrix
conf= print(confusion_matrix(y_test,y_pred))

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
Decimod=DecisionTreeClassifier(max_leaf_nodes=10,random_state=0)
Decimod.fit(X_train,y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [38]:
y_predi= Decimod.predict(X_test)

In [42]:
Decimod.score(X_test,y_test) #Accuracy 74.5%

0.7445887445887446

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
confma=print(confusion_matrix(y_test,y_predi))

[[126  18]
 [ 41  46]]